### ISSUE TITLE
Scheduled report mailed 8 times

### ISSUE THREAD

**Issue by sidneydemoraes** [d4software/QueryTree#32]
Hi there.

Just found one more thing. I wish i knew .Net so I could send you PRs.

I scheduled a report to be mailed daily at 10AM. At 9:33AM I received 8 (eight) emails with the very same report.

Let me know if you need any additional information or tests.

**Comment by dand4** [comment]
I've been looking into this. I've discovered that it's something to do with the [Hangfire.SQLite](https://github.com/wanlitao/HangfireExtension) package. When I switched to Hangfire.MemoryStorage it worked OK. I will keep investigating.

**Comment by dand4** [comment]
@sidneydemoraes this issue should now be fixed in the latest master.

**Comment by ohbert** [comment]
I have the same problem with the scheduled email with the latest version (downloaded 24th of October 2019). Every mail is being sent 20 times. I run the application on Ubuntu 18.04 server and SQLite. Is there a logfile I can share to investigate the problem?

**Comment by changchichung** [comment]
> I have the same problem with the scheduled email with the latest version (downloaded 24th of October 2019). Every mail is being sent 20 times. I run the application on Ubuntu 18.04 server and SQLite. Is there a logfile I can share to investigate the problem?

and I can confirm this situation with latest docker version querytree , every mail sent 20 times.

**Comment by matrh88** [comment]
I still have the issue that the scheduled reports get sent out 13-20 times, but I have tried solving the issue within the source code. From what I can gather, the statement
`if (!_messageDeliveryTime.TryGetValue(messageId, out deliveredTime) || deliveredTime.AddSeconds(TimeoutInSeconds) <= DateTime.UtcNow)`
always comes out to true until the function `TrySetDelivered()` has been run a couple of times.
I do not know if the issue might lie here. would be great if this could be researched further. @d4nt

**Comment by fabiotofy** [comment]
Hi,
i have download the latest version of software on june 2020 but i have the same problem: when i scheduled a reports for to send by email, this reports arrived 6 (six) times. How can i resolve the problem ?

Thanks

**Comment by SysEngDan** [comment]
@d4nt - Any thoughts on https://github.com/d4software/QueryTree/issues/32#issuecomment-640559040
